title: Leonardo Placidi
description: Selected projects and technical notes
theme: minima
# minimal links in header
minima:
  social_links:
    - { platform: linkedin,  user_url: "https://www.linkedin.com/in/leonardo-p-570616198/" }
    - { platform: github,    user_url: "https://github.com/Gruntrexpewrus" }
